[build]
  publish = "web"
  command = "node build-inject-env.js"

# Environment variables will be set in Netlify dashboard
# GOOGLE_MAPS_API_KEY = "your-api-key-here"

[build.environment]
  NODE_ENV = "production"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# HTML files - NO CACHE (always fresh)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Root index - NO CACHE
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets (JS/CSS with versioning)
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Images cache for 1 week
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Redirects
[[redirects]]
  from = "/admin"
  to = "/admin-login.html"
  status = 301

[[redirects]]
  from = "/restaurant"
  to = "/restaurant-login.html"
  status = 301

# SPA fallback - ONLY for non-existing files (404s)
# Static files (CSS, JS, images) should NOT be redirected
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false