[build]
  publish = "web"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin-panel/*"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/restaurant-panel/*"
  to = "/restaurant-panel.html"
  status = 200

[[redirects]]
  from = "/restaurant-login/*"
  to = "/restaurant-login.html"
  status = 200

[[redirects]]
  from = "/restaurant/*"
  to = "/restaurant-login.html"
  status = 200

[[redirects]]
  from = "/customer-registration.html"
  to = "/customer-registration.html"
  status = 200

[[redirects]]
  from = "/customer-registration"
  to = "/customer-registration.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/customer-registration.html"
  status = 200

[[redirects]]
  from = "/kayit"
  to = "/customer-registration.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
