services:
  - type: web
    name: kaptaze-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://kaptaze-admin:kaptaze2024@kaptaze.v8dqkng.mongodb.net/kaptazeappv5?retryWrites=true&w=majority
      - key: JWT_SECRET  
        value: kaptaze_jwt_secret_production_2024_secure_key_v1
      - key: CORS_ORIGIN
        value: https://kaptaze.netlify.app,https://kaptaze-admin.netlify.app,https://kaptaze-customer.netlify.app,https://kaptaze-restaurant.netlify.app