[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Redirects for clean URLs
[[redirects]]
  from = "/customer-registration"
  to = "/customer-registration.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-login.html" 
  status = 200

[[redirects]]
  from = "/admin-panel"
  to = "/admin-panel.html"
  status = 200

[[redirects]]
  from = "/restaurant"
  to = "/restaurant-login.html"
  status = 200

[[redirects]]
  from = "/restaurant-panel"
  to = "/restaurant-panel.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/customer-registration.html"
  status = 200

[[redirects]]
  from = "/kayit"
  to = "/customer-registration.html"
  status = 200

# API now handled by Render backend - no local functions needed

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"